# Farben von Pywal laden
include ~/.cache/wal/colors-kitty.conf

font_family      JetBrainsMono Nerd Font
font_size        12.0

window_padding_width 15
background_opacity 0.8
hide_window_decorations yes

# FIX: Nutzt 'color1' ohne @ Zeichen
cursor           color1
cursor_shape     beam
mouse_hide_wait  3.0

shell_integration enabled